// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: PaqueteLogCam/PaqueteLogCam.proto

package PaqueteLogCam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDPaquete string `protobuf:"bytes,1,opt,name=IDPaquete,proto3" json:"IDPaquete,omitempty"`
	Tipo      string `protobuf:"bytes,2,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Valor     int32  `protobuf:"varint,3,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Origen    string `protobuf:"bytes,4,opt,name=Origen,proto3" json:"Origen,omitempty"`
	Destino   string `protobuf:"bytes,5,opt,name=Destino,proto3" json:"Destino,omitempty"`
	Intentos  int32  `protobuf:"varint,6,opt,name=Intentos,proto3" json:"Intentos,omitempty"`
	Estado    string `protobuf:"bytes,7,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_PaqueteLogCam_PaqueteLogCam_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetIDPaquete() string {
	if x != nil {
		return x.IDPaquete
	}
	return ""
}

func (x *Message) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Message) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Message) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Message) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Message) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Message) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_PaqueteLogCam_PaqueteLogCam_proto_rawDescGZIP(), []int{1}
}

var File_PaqueteLogCam_PaqueteLogCam_proto protoreflect.FileDescriptor

var file_PaqueteLogCam_PaqueteLogCam_proto_rawDesc = []byte{
	0x0a, 0x21, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x2f,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43,
	0x61, 0x6d, 0x22, 0xb7, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x49, 0x44, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x49, 0x44, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x70, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x95, 0x01, 0x0a, 0x14, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c,
	0x0a, 0x0a, 0x41, 0x73, 0x6b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x14, 0x2e, 0x50,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x16, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43,
	0x61, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0d,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4c,
	0x6f, 0x67, 0x43, 0x61, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x53, 0x6f, 0x6c,
	0x61, 0x72, 0x56, 0x2f, 0x54, 0x61, 0x72, 0x65, 0x61, 0x31, 0x2f, 0x50, 0x61, 0x71, 0x75, 0x65,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PaqueteLogCam_PaqueteLogCam_proto_rawDescOnce sync.Once
	file_PaqueteLogCam_PaqueteLogCam_proto_rawDescData = file_PaqueteLogCam_PaqueteLogCam_proto_rawDesc
)

func file_PaqueteLogCam_PaqueteLogCam_proto_rawDescGZIP() []byte {
	file_PaqueteLogCam_PaqueteLogCam_proto_rawDescOnce.Do(func() {
		file_PaqueteLogCam_PaqueteLogCam_proto_rawDescData = protoimpl.X.CompressGZIP(file_PaqueteLogCam_PaqueteLogCam_proto_rawDescData)
	})
	return file_PaqueteLogCam_PaqueteLogCam_proto_rawDescData
}

var file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PaqueteLogCam_PaqueteLogCam_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: PaqueteLogCam.Message
	(*Empty)(nil),   // 1: PaqueteLogCam.Empty
}
var file_PaqueteLogCam_PaqueteLogCam_proto_depIdxs = []int32{
	1, // 0: PaqueteLogCam.PaqueteLogCamService.AskPackage:input_type -> PaqueteLogCam.Empty
	0, // 1: PaqueteLogCam.PaqueteLogCamService.FinishPackage:input_type -> PaqueteLogCam.Message
	0, // 2: PaqueteLogCam.PaqueteLogCamService.AskPackage:output_type -> PaqueteLogCam.Message
	1, // 3: PaqueteLogCam.PaqueteLogCamService.FinishPackage:output_type -> PaqueteLogCam.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PaqueteLogCam_PaqueteLogCam_proto_init() }
func file_PaqueteLogCam_PaqueteLogCam_proto_init() {
	if File_PaqueteLogCam_PaqueteLogCam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PaqueteLogCam_PaqueteLogCam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PaqueteLogCam_PaqueteLogCam_proto_goTypes,
		DependencyIndexes: file_PaqueteLogCam_PaqueteLogCam_proto_depIdxs,
		MessageInfos:      file_PaqueteLogCam_PaqueteLogCam_proto_msgTypes,
	}.Build()
	File_PaqueteLogCam_PaqueteLogCam_proto = out.File
	file_PaqueteLogCam_PaqueteLogCam_proto_rawDesc = nil
	file_PaqueteLogCam_PaqueteLogCam_proto_goTypes = nil
	file_PaqueteLogCam_PaqueteLogCam_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PaqueteLogCamServiceClient is the client API for PaqueteLogCamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaqueteLogCamServiceClient interface {
	AskPackage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error)
	FinishPackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type paqueteLogCamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaqueteLogCamServiceClient(cc grpc.ClientConnInterface) PaqueteLogCamServiceClient {
	return &paqueteLogCamServiceClient{cc}
}

func (c *paqueteLogCamServiceClient) AskPackage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/PaqueteLogCam.PaqueteLogCamService/AskPackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paqueteLogCamServiceClient) FinishPackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/PaqueteLogCam.PaqueteLogCamService/FinishPackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaqueteLogCamServiceServer is the server API for PaqueteLogCamService service.
type PaqueteLogCamServiceServer interface {
	AskPackage(context.Context, *Empty) (*Message, error)
	FinishPackage(context.Context, *Message) (*Empty, error)
}

// UnimplementedPaqueteLogCamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaqueteLogCamServiceServer struct {
}

func (*UnimplementedPaqueteLogCamServiceServer) AskPackage(context.Context, *Empty) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskPackage not implemented")
}
func (*UnimplementedPaqueteLogCamServiceServer) FinishPackage(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishPackage not implemented")
}

func RegisterPaqueteLogCamServiceServer(s *grpc.Server, srv PaqueteLogCamServiceServer) {
	s.RegisterService(&_PaqueteLogCamService_serviceDesc, srv)
}

func _PaqueteLogCamService_AskPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteLogCamServiceServer).AskPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PaqueteLogCam.PaqueteLogCamService/AskPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteLogCamServiceServer).AskPackage(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaqueteLogCamService_FinishPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteLogCamServiceServer).FinishPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PaqueteLogCam.PaqueteLogCamService/FinishPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteLogCamServiceServer).FinishPackage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaqueteLogCamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PaqueteLogCam.PaqueteLogCamService",
	HandlerType: (*PaqueteLogCamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskPackage",
			Handler:    _PaqueteLogCamService_AskPackage_Handler,
		},
		{
			MethodName: "FinishPackage",
			Handler:    _PaqueteLogCamService_FinishPackage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PaqueteLogCam/PaqueteLogCam.proto",
}
